module: LaunchDarkly
author: LaunchDarkly
author_url: https://launchdarkly.com
github_url: https://github.com/launchdarkly/ios-client-sdk
clean: true
swift_build_tool: spm
readme: README.md
documentation:
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE.txt

copyright: 'Copyright © 2019 Catamorphic Co.'

custom_categories:
  - name: Core Classes
    children:
    - LDClient
    - LDConfig
    - LDContext
    - LDContextBuilder
    - LDUser
    - Reference
    - LDMultiContextBuilder
    - LDEvaluationDetail
    - LDValue

  - name: Flag Change Observers
    children:
    - LDObserverOwner
    - LDChangedFlag
    - LDFlagChangeHandler
    - LDFlagCollectionChangeHandler
    - LDFlagsUnchangedHandler

  - name: Connection Information
    children:
    - ConnectionInformation
    - LDConnectionModeChangedHandler

  - name: Other Types
    children:
    - LDStreamingMode
    - LDFlagKey
    - LDInvalidArgumentError
    - RequestHeaderTransform

  - name: Objective-C Core Interfaces
    children:
    - ObjcLDClient
    - ObjcLDConfig
    - ObjcLDReference
    - ObjcLDContext
    - ObjcLDChangedFlag
    - ObjcLDUser
    - ObjcLDValue
    - ObjcLDValueType

  - name: Objective-C EvaluationDetail Wrappers
    children:
    - ObjcLDBoolEvaluationDetail
    - ObjcLDIntegerEvaluationDetail
    - ObjcLDDoubleEvaluationDetail
    - ObjcLDStringEvaluationDetail
    - ObjcLDJSONEvaluationDetail
